name: calendar_example
description: Example of how to use the calendar widget.

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_native_timezone: ">=2.0.0 <3.0.0"
  sliver_calendar:
    path: ../
  timezone: ">=0.8.0 <1.0.0"
  cupertino_icons: ">=1.0.3 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  mockito: ^5.0.16
  golden_toolkit: ^0.11.0


flutter:
  uses-material-design: true

  assets:
       - assets/timezone/2018c.tzf
       - assets/images/calendarbanner.jpg
       - assets/images/calendarheader.png
