name: sliver_calendar
description: Display a calendar view for flutter.
version: 1.0.0
homepage: https://github.com/pinkfish/flutter_calendar

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  timezone: ^0.8.0
  clock: ^1.1.0

dev_dependencies:
  test: ^1.16.5
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

